### ISSUE TITLE
文档看不到了

### ISSUE THREAD

**Issue by freedom-wy** [WAY29/Doughnuts#11]
你好，这个域名doughnuts.cc可能是过期了，文档看不到了
另外我拉取的代码中没有找到variables.config这个配置文件

**Comment by WAY29** [comment]
> 你好，这个域名doughnuts.cc可能是过期了，文档看不到了
> 另外我拉取的代码中没有找到variables.config和config.ini这两个配置文件

是的域名好像这几天过期了,我会更新README,有空会重写文档,旧文档的地址在https://doughnuts3.gitbook.io/
另外variables.config这个配置文件是可选的,没有这些配置文件不影响程序的的正常运行

**Comment by freedom-wy** [comment]
config.ini我找到了
